### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by incandescant** [rleitner/language-bb#1]
This repository doesn't have a license, which makes contributing more difficult. Please add a license as I've implemented the two features from the TODO.

language-perl and language-make both seem to have a MIT-like license, which seems like a fine choice :smile:

**Comment by g0hl1n** [comment]
Thanks for the hint. MIT should be fine so I've added it as license.

**Comment by ghost** [comment]
Thanks for the hint. MIT should be fine so I've added it as license.
