### ISSUE TITLE
Syntax highlighting bug

### ISSUE THREAD

**Issue by rossburton** [rleitner/language-bb#3]
The following bbclass snipped causes the highlighting to go all wrong.  Note how the FOO=bar assignments are coloured differently under language-bb.

```
FOO = "bar"

def some_python_function(d):
    bb.warn(u"PE = %s", "epoch")

FOO = "bar"
```

The highlighting parser sees PE = in the python block and decides that its a bitbake variable assignment.

**Comment by ghost** [comment]
Thanks for the report.

After a little bit of testing I noticed that adding a space before the first double quote in the python function lets language-bb highlight the function correctly:

```
FOO = "bar"

def some_python_function(d):
    bb.warn(u "PE = %s", "epoch")

FOO = "bar"
```

Therefore it seems there's something wrong with the string/double-quote parsing.

**Comment by rossburton** [comment]
I've replaced my 0.2.1 install of language-bb with a git clone but this still breaks for me.

The original source of the bad formatting was meta/classes/buildhistory.bbclass, in the write_recipeinfo function (oe-core git master).

**Comment by ghost** [comment]
Thanks for testing, you're right. The following snippet is still parsed incorrectly:

```
FOO = "bar"

def write_recipehistory(rcpinfo, d):
    import codecs

    bb.debug(2, "Writing recipe history")

    pkghistdir = d.getVar('BUILDHISTORY_DIR_PACKAGE', True)

    infofile = os.path.join(pkghistdir, "latest")
    with codecs.open(infofile, "w", encoding='utf8') as f:
        if rcpinfo.pe != "0":
            f.write(u"PE = %s\n" %  rcpinfo.pe)
        f.write(u"PV = %s\n" %  rcpinfo.pv)
        f.write(u"PR = %s\n" %  rcpinfo.pr)
        f.write(u"DEPENDS = %s\n" %  rcpinfo.depends)
        f.write(u"PACKAGES = %s\n" %  rcpinfo.packages)

FOO = "bar"
```

Looks like that problem is caused by the empty newline in the python function.
Following snippet is parsed correctly:

```
FOO = "bar"

def write_recipehistory(rcpinfo, d):
    import codecs
    bb.debug(2, "Writing recipe history")
    pkghistdir = d.getVar('BUILDHISTORY_DIR_PACKAGE', True)
    infofile = os.path.join(pkghistdir, "latest")
    with codecs.open(infofile, "w", encoding='utf8') as f:
        if rcpinfo.pe != "0":
            f.write(u"PE = %s\n" %  rcpinfo.pe)
        f.write(u"PV = %s\n" %  rcpinfo.pv)
        f.write(u"PR = %s\n" %  rcpinfo.pr)
        f.write(u"DEPENDS = %s\n" %  rcpinfo.depends)
        f.write(u"PACKAGES = %s\n" %  rcpinfo.packages)

FOO = "bar"
```
