### ISSUE TITLE
SRC_URI = "git://(address)" is not highlighted in purple

### ISSUE THREAD

**Issue by zpfvo** [rleitner/language-bb#5]
Hi,
when there is:
`SRC_URI = "file://<path>"`
everything in quotes is printed in purple. 
But when used the git fetcher:
`SRC_URI = "git://<address>"`
text inside quotes is printed in green, like a variable assignment.

**Comment by ghost** [comment]
Hi,
thanks for testing language-bb and reporting that problem!
Unfortunately I'm not able to reproduce that issue with following example:
![screenshot - 04222016 - 09 27 42 am](https://cloud.githubusercontent.com/assets/4919312/14734705/87d8f796-086c-11e6-8ac5-e51df1edd6a0.png)

Can you please provide a file/example where that problem occurs?

**Comment by zpfvo** [comment]
Hi,

for example:

![language-bb-screenshot](https://cloud.githubusercontent.com/assets/13163514/14735236/16d861e0-0870-11e6-8393-4a1801e4712d.png)

But i was not able to find one occurrence of git being highlighted correctly in my source folder.
I'am using version 0.2.2 and Atom 1.7.2.

**Comment by ghost** [comment]
That looks like some kind of "URI to Hyperlink" stuff to me.
language-bb doesn't implement such a feature.
Which other plugins do you have installed?

**Comment by zpfvo** [comment]
ah i didnt think of that :/

apm list gives me:
Community Packages (21)
├── atom-sync@0.7.3
├── autocomplete-python@1.7.2
├── autocomplete-ruby@0.1.0
├── file-icons@1.7.6
├── git-go@1.0.2
├── language-bb@0.2.2
├── language-diff@0.4.0
├── linter@1.11.4
├── linter-flake8@1.13.0
├── linter-rubocop@0.4.7
├── linter-ruby@1.2.2
├── minimap@4.22.1
├── minimap-cursorline@0.1.0
├── minimap-find-and-replace@4.5.1
├── minimap-linter@1.1.1
├── python-autopep8@0.1.3
├── python-indent@0.4.3
├── python-isort@0.0.7
├── python-tools@0.6.7
├── ruby-block@0.3.5
└── split-diff@0.7.5

But i dont have an idea which packet might cause this behaviour

**Comment by zpfvo** [comment]
I think i found it. its probably:
language-hyperlink. its a core package.
I'm sry  :/

**Comment by ghost** [comment]
No problem ;-)
Does it parse correctly if you disable language-hyperlink?

**Comment by zpfvo** [comment]
Yes, when disabled everything is highlighted like intended.

But highlighting source strings might be a neat feature for the future ;)
